// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj-oS9N1U69kTIh_l2Q_Sz_0mnfbEvejQ',
    appId: '1:22170743547:web:06171a608682088f89f65e',
    messagingSenderId: '22170743547',
    projectId: 'whatbytetaskapp',
    authDomain: 'whatbytetaskapp.firebaseapp.com',
    storageBucket: 'whatbytetaskapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSehVok7P6IcTPAbOi_YksRRJqPktGUj8',
    appId: '1:22170743547:android:706c8ec385aba83189f65e',
    messagingSenderId: '22170743547',
    projectId: 'whatbytetaskapp',
    storageBucket: 'whatbytetaskapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9yHdMObbUCnc1Eh2X_TOddLrKlOX3LSQ',
    appId: '1:22170743547:ios:cfee1f35dc8d048c89f65e',
    messagingSenderId: '22170743547',
    projectId: 'whatbytetaskapp',
    storageBucket: 'whatbytetaskapp.firebasestorage.app',
    iosBundleId: 'com.example.whatbytestaskapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9yHdMObbUCnc1Eh2X_TOddLrKlOX3LSQ',
    appId: '1:22170743547:ios:cfee1f35dc8d048c89f65e',
    messagingSenderId: '22170743547',
    projectId: 'whatbytetaskapp',
    storageBucket: 'whatbytetaskapp.firebasestorage.app',
    iosBundleId: 'com.example.whatbytestaskapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj-oS9N1U69kTIh_l2Q_Sz_0mnfbEvejQ',
    appId: '1:22170743547:web:7f6777a9a6c9fb8f89f65e',
    messagingSenderId: '22170743547',
    projectId: 'whatbytetaskapp',
    authDomain: 'whatbytetaskapp.firebaseapp.com',
    storageBucket: 'whatbytetaskapp.firebasestorage.app',
  );
}
